### ISSUE TITLE
Consumer when using Kafka Transport fails to start

### ISSUE THREAD

**Issue by mwagers** [pablocastilla/NServiceBus.Kafka#15]
I have successfully sent a message using NServiceBus configure with a Kafka Transport, but am unable to receive the message unless listening to Kafka outside of NServiceBus. The following code blows up in a console app:

`var endpointConfiguration = new EndpointConfiguration("Sales");

			var transport = endpointConfiguration.UseTransport<KafkaTransport>();
			transport.ConnectionString("127.0.0.1:9092");

			endpointConfiguration.UseSerialization<JsonSerializer>();
			endpointConfiguration.UsePersistence<InMemoryPersistence>();
			endpointConfiguration.SendFailedMessagesTo("error");
			endpointConfiguration.EnableInstallers();

			var endpointInstance = await Endpoint.Start(endpointConfiguration).ConfigureAwait(false);

			Console.WriteLine("Press Enter to exit...");
			Console.ReadLine();
`

The error indicated is: 2017-03-14 14:23:37.032 WARN  NServiceBus.Transport.Kafka.Receiving.MessagePump System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NServiceBus.Transport.Kafka.Receiving.QueueCreator.<CreateQueueIfNecessary>d__3.MoveNext()

I'm using NServiceBus 6.1.3 and the latest Kafka Transport library from NuGet.

**Comment by pablocastilla** [comment]
Happy to see my first user. 

The code had a bug, it must work in the latest nuget I have just uploaded.

Please tell me if it works.

Thanks for using.

**Comment by mwagers** [comment]
Thank you for such a quick response.

The project starts with 0 errors/warnings now, but I am not getting the IHandleMessages<...> fired when a message is put on the bus. This did happen when using SqlTransport.

**Comment by pablocastilla** [comment]
Could you try removing "sales" and creating a topic with the default service name?

Anyhow tomorrow morning I will try to see what's hapenning.

**Comment by mwagers** [comment]
I'm not 100% clear on what you mean by the default service name? I'm actually using the NServiceBus sample lessons to work this out, so the actual program is "Sales.exe". I have this in my Producer, if it helps:

`var endpointConfiguration = new EndpointConfiguration("ClientUI");
						
			var transport = endpointConfiguration.UseTransport<KafkaTransport>();
			transport.ConnectionString("127.0.0.1:9092");

			var routing = transport.Routing();
			routing.RouteToEndpoint(typeof(C.PlaceOrder), "test");

			endpointConfiguration.UseSerialization<JsonSerializer>();
			endpointConfiguration.UsePersistence<InMemoryPersistence>();
			//endpointConfiguration.SendFailedMessagesTo("error");
			endpointConfiguration.SendOnly();
			endpointConfiguration.EnableInstallers();

			var endpointInstance = await Endpoint.Start(endpointConfiguration).ConfigureAwait(false);

			Console.Write("Press Enter to exit...");
			Console.ReadLine();

			await RunLoop(endpointInstance);

			await endpointInstance.Stop().ConfigureAwait(false);
`

**Comment by pablocastilla** [comment]
I have been testing the examples in my machine and it works. I think the problem is here:

routing.RouteToEndpoint(typeof(C.PlaceOrder), "test"); <-- do you have an endpoint called test?

Which example are you using? there are a few of them.

**Comment by mwagers** [comment]
You are correct, that code was from some other trial and error work. It does work now. I am getting warnings about offset removal whenever I get a message though:

2017-03-15 08:02:30.749 WARN  NServiceBus.Transports.Kafka.Connection.ConsumerHolder offset received cound not be removed from list

I'm not sure that is important and may be a residual side effect of earlier messages.

I'm very pleased to see this working and it is a big step for us. I appreciate your help!

**Comment by pablocastilla** [comment]
Yes, I will set that message as info instead of warning.

Thanks for reporting the problem.
