### ISSUE TITLE
Support for NServiceBus v7?

### ISSUE THREAD

**Issue by andreasohlund** [pablocastilla/NServiceBus.Kafka#18]
With v7 just right around the corner are there any plans to update the transport to support it? (there should not be any dramatic changes on the transport seam)

Let let me know if you need any help

**Comment by pablocastilla** [comment]
Hi!

In the future I see migrating it to confluent driver but only when the exactly-once gets supported.
https://github.com/edenhill/librdkafka/issues/1308 

Anyhow I don't have a lot of time right now, let me check how much time would it cost me. If it is really easy I could do it.

Regards

**Comment by andreasohlund** [comment]
No preassure from my end just wanted to give a heads up and offer my
assistance if needed

**Comment by pablocastilla** [comment]
Thanks!

**Comment by bbrandt** [comment]
Looks like https://github.com/confluentinc/librdkafka/issues/1308 was completed.  Just an observation.
https://github.com/confluentinc/librdkafka/issues/1308#issuecomment-608085254
