### ISSUE TITLE
What's the trick to change the transport in the acceptance tests?

### ISSUE THREAD

**Issue by pablocastilla** [pablocastilla/NServiceBus.Kafka#2]
Hi @danielmarbach @janovesk!

I would like to know how do you change the transport in the **acceptance tests** and **transport tests**. How do you tell, for instance , in the rabbit transport to use the rabbit instead of msmq. I don't get it.

Could you forward this to someone in particular that know it?

Thanks

**Comment by danielmarbach** [comment]
Environment variable Transport.UseSpecific

Sorry day off will write more tomorrow

**Comment by pablocastilla** [comment]
Hi Daniel, thanks for answering in your day off.

The problem, maybe it is obvious, is that I don't see is how it is set and at the end MSMQ is tested.

**Comment by danielmarbach** [comment]
Here is how I let ASQ tests run for example

User variable `AzureStorageQueueTransport.ConnectionString` and
`Transport.UseSpecific` with `AzureStorageQueueTransport`

**Comment by pablocastilla** [comment]
I don't want you to consider me dumb... but I don't find where do you set it :S

**Comment by pablocastilla** [comment]
Okok, now it works  :)

**Comment by danielmarbach** [comment]
was just about to paste some windows screenshots ;)

**Comment by pablocastilla** [comment]
well, do it please. At the end I have modified the DefautServer class and put this in it

            settings.Set("Transport", typeof(KafkaTransport));
            var types = endpointConfiguration.GetTypesScopedByTestClass();

If I don't do this the App_Packages tests are executed under msmq.

**Comment by danielmarbach** [comment]
![image](https://cloud.githubusercontent.com/assets/174258/21455486/ddd071cc-c920-11e6-9ede-6c865a04b167.png)

![image](https://cloud.githubusercontent.com/assets/174258/21455504/02e51a58-c921-11e6-854d-063e2fc21c6b.png)

![image](https://cloud.githubusercontent.com/assets/174258/21455509/13ef421a-c921-11e6-88fc-c628057913af.png)

**Comment by pablocastilla** [comment]
Ooooooook. I thought about that but didn't find any info. Thanks! 

I have created the nuget, it sends and publishes but with a lot of bugs, still a lot of work to do but getting closer.
