### ISSUE TITLE
in the acceptance tests with addmapping it doesn't find any handler

### ISSUE THREAD

**Issue by pablocastilla** [pablocastilla/NServiceBus.Kafka#3]
Hi @danielmarbach @janovesk!

I hope you can help me with this issue that is making me crazy.

The problem is that when I use acceptance tests with addmapping I always get (for instance): 
"No handlers could be found for message type: NServiceBus.AcceptanceTests.Basic.When_sending_to_another_endpoint+MyMessage"

I don't know what I am doing wrong.

Do you know what could be the reason for this?

Thanks.

**Comment by pablocastilla** [comment]
forget it :)

**Comment by danielmarbach** [comment]
Sorry was on vacation and only returned this week for the company meeting. Will be more responsive now

**Comment by pablocastilla** [comment]
No problem. And you still can help me :)

 The problem with the following sequence:

1.- Message is sent in the acceptance test When_sending_to_another_endpoint to the Receiver topic
2.- Message is processed ok
3.- An audit message is generated and also
4.- The initial message is sent again to the Receiver topic and everything fails because everything is shuting down. This happens I think out of my code, so I am lost.

If I disable auditing in the DefaultServer everything works.

Say hi to Sean Farmar :)

**Comment by danielmarbach** [comment]
Can you give me a quick heads up what is the quickest way to get the acceptance test executed on my machine? I could setup a kafka node on Azure or use https://bitnami.com/stack/kafka/virtual-machine. What would you recommend?

**Comment by pablocastilla** [comment]
I have prepared my kafka for you here:
https://1drv.ms/u/s!Av_YzZiT16fZgv067XJot9CeEjpjVA 

Unzip it in your machine in C:\

1.- Execute zkServer.cmd in c:\zookeeper-3.4.8\bin
2.- Execute .\kafka-server-start.bat .\server.properties in C:\kafka_2.11-0.10.1.0\bin\windows
3.- Set in your environemtn the following user variables 
        - Transport.UseSpecific: KafkaTransport
        - KafkaTransport.ConnectionString: 127.0.0.1:9092

Execute any test you want :)

Thanks!

**Comment by pablocastilla** [comment]
I recommend you this tool: http://www.kafkatool.com/

**Comment by pablocastilla** [comment]
After creating one consumer per test endpoint it seems to work at least in debugging. 

I have problems stopping things, tomorrow I will have a look at them. At least now I have some green dots.

I will close this issue.

Thanks!
