### ISSUE TITLE
Exception when defering messages

### ISSUE THREAD

**Issue by pablocastilla** [pablocastilla/NServiceBus.Kafka#4]
Hi @danielmarbach !

I have a problem and I am not able to fix it. It is related to defering messages. 

When I defer any message I have an exception related to a header called "Timeout.Id" but I don't know how to generate it and I don't find it in other transports.

What am I missing? 

Thanks and have a good weekend!

Exception when executing When_deferring_to_non_local.Message_should_be_received:

Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
error onMessage: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NServiceBus.DispatchTimeoutBehavior.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\DispatchTimeoutBehavior.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.Transport.Kafka.Receiving.MessagePump.<Process>d__23.MoveNext() in C:\Users\sesa221523\Source\Repos\NServiceBus.Kafka\src\NServiceBus.Kafka\Receiving\MessagePump.cs:line 232

**Comment by danielmarbach** [comment]
Do you support native delayed delivery or do you need the timeout manager? If you want to support native delayed delivery you can indicate that by returning the proper list of constraints

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Config/AzureServiceBusTransportInfrastructure.cs#L75

If you don't specify `DelayDeliveryWith` you need the timeout manager for delayed delivery. But the exception is rather odd and not helpful. I'll investigate a bit more.

**Comment by pablocastilla** [comment]
Thanks for helping!

The idea is to use the timeout manager. If I enable it it crashes :(

**Comment by danielmarbach** [comment]
I think I found the issue. NServiceBus makes the following assumptions:

Every time the core needs a message pump it is going to call on the transport receive infrastructure the pump factory `TransportReceiveInfrastructure.MessagePumpFactory()` then it initializes it and at a certain point the pump will be started. This happens for the main pipeline and for all the satellites. In your case you are creating a singleton message pump. Your start method already has code in it which assumes that Start is going to be called multiple times. But as a matter of fact, core will also initialize your singleton multiple times and pass in the pipeline func delegates for the main pipeline or the satellite it is creating. For the timeout, manager to work you need two pumps. One for the main pipeline (the func passed into the init method will be the main pipeline execution func) and one for the timeout pipeline (the func will represent that satellite pipeline func). Only then timeout manager will work. 

In essence, change your code to no longer make the pump a singleton per transport infrastructure and use the settings passed into the init of the pump to setup your topics accordingly. I'm travelling today, but I will try to send in a quick demonstration PR.

**Comment by pablocastilla** [comment]
Now it works :).

Thanks for the information

**Comment by danielmarbach** [comment]
You are a bit too fast. Was just about to send in this https://github.com/pablocastilla/NServiceBus.Kafka/pull/7
