### ISSUE TITLE
ConsumerHolder Continuation missuse and missing await

### ISSUE THREAD

**Issue by danielmarbach** [pablocastilla/NServiceBus.Kafka#8]
The consumer holder uses

https://github.com/pablocastilla/NServiceBus.Kafka/blob/master/src/NServiceBus.Kafka/Connection/ConsumerHolder.cs#L186

and specifies `ExecuteSynchronously` 

https://github.com/pablocastilla/NServiceBus.Kafka/blob/master/src/NServiceBus.Kafka/Connection/ConsumerHolder.cs#L229

although it actually executes IO-bound work

https://github.com/pablocastilla/NServiceBus.Kafka/blob/master/src/NServiceBus.Kafka/Connection/ConsumerHolder.cs#L225

There are multiple problems due to that:

If you stick to that pattern you have to remove the `ExecuteSynchronously` since you are violating the TPL constraints that a continuation with that flag should only execute synchronous and really short lived operations as well as mark the lambda as `async` and properly `await` the commit. If you don't do that you'll never find out when the commit fails

but overall I think this code is unnecessarily complex since you could write the same code inside the Process method with normal async await pattern 

https://github.com/pablocastilla/NServiceBus.Kafka/blob/master/src/NServiceBus.Kafka/Connection/ConsumerHolder.cs#L262

**Comment by pablocastilla** [comment]
I see your point. You have a good eye for asynchrony in c#. 

As this is related to: 
https://github.com/pablocastilla/NServiceBus.Kafka/issues/9

How do you see just isnerting the processed offset in the collection in the continuewith and do the batch processing each X milliseconds in another task? (let's continue this conversation in 9)

**Comment by danielmarbach** [comment]
@pablocastilla maybe it is best we have a quick call and discuss the ideas. my skype is the same as my github username
